### ISSUE TITLE
question on V3 i2c

### ISSUE THREAD

**Issue by chaeplin** [elechouse/VoiceRecognitionV3#2]
I have bought http://www.elechouse.com/elechouse/index.php?main_page=product_info&cPath=168_170&products_id=2254 V3.

Back side has i2c port print. Does V3 module support i2c ?

**Comment by wilson-elechouse** [comment]
No, Sir
It only support serial port

2015-07-14 11:59 GMT+08:00 chaeplin <notifications@github.com>:

**Comment by chaeplin** [comment]
Thank you
