### ISSUE TITLE
Copy trained Recognizer from one module to another module

### ISSUE THREAD

**Issue by phiard** [elechouse/VoiceRecognitionV3#28]
Hi, Is it possible to copy a trained vr module to another empty vr module?
So that we don't have to re-train it again

**Comment by zaid-alrowaili** [comment]
I have a problem saving the audio can you help me 
![6D9A96F7-122D-4A03-ABA0-94F8253CA41C](https://github.com/elechouse/VoiceRecognitionV3/assets/145748103/a08fead7-171e-48e1-840c-7b30dba0b67c)

**Comment by khaled312001** [comment]
Did you find any solution?

**Comment by phiard** [comment]
no solution, i just individually train the modules
